// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloudreve/Cloudreve/v4/ent/abusereport"
)

// AbuseReport is the model entity for the AbuseReport schema.
type AbuseReport struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// ReporterID holds the value of the "reporter_id" field.
	ReporterID int `json:"reporter_id,omitempty"`
	// ReporterEmail holds the value of the "reporter_email" field.
	ReporterEmail string `json:"reporter_email,omitempty"`
	// TargetType holds the value of the "target_type" field.
	TargetType string `json:"target_type,omitempty"`
	// TargetID holds the value of the "target_id" field.
	TargetID int `json:"target_id,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason int `json:"reason,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AdminNote holds the value of the "admin_note" field.
	AdminNote    string `json:"admin_note,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AbuseReport) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case abusereport.FieldID, abusereport.FieldReporterID, abusereport.FieldTargetID, abusereport.FieldReason:
			values[i] = new(sql.NullInt64)
		case abusereport.FieldReporterEmail, abusereport.FieldTargetType, abusereport.FieldDescription, abusereport.FieldStatus, abusereport.FieldAdminNote:
			values[i] = new(sql.NullString)
		case abusereport.FieldCreatedAt, abusereport.FieldUpdatedAt, abusereport.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AbuseReport fields.
func (ar *AbuseReport) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case abusereport.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ar.ID = int(value.Int64)
		case abusereport.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ar.CreatedAt = value.Time
			}
		case abusereport.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ar.UpdatedAt = value.Time
			}
		case abusereport.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				ar.DeletedAt = new(time.Time)
				*ar.DeletedAt = value.Time
			}
		case abusereport.FieldReporterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reporter_id", values[i])
			} else if value.Valid {
				ar.ReporterID = int(value.Int64)
			}
		case abusereport.FieldReporterEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reporter_email", values[i])
			} else if value.Valid {
				ar.ReporterEmail = value.String
			}
		case abusereport.FieldTargetType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_type", values[i])
			} else if value.Valid {
				ar.TargetType = value.String
			}
		case abusereport.FieldTargetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_id", values[i])
			} else if value.Valid {
				ar.TargetID = int(value.Int64)
			}
		case abusereport.FieldReason:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				ar.Reason = int(value.Int64)
			}
		case abusereport.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				ar.Description = value.String
			}
		case abusereport.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ar.Status = value.String
			}
		case abusereport.FieldAdminNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field admin_note", values[i])
			} else if value.Valid {
				ar.AdminNote = value.String
			}
		default:
			ar.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AbuseReport.
// This includes values selected through modifiers, order, etc.
func (ar *AbuseReport) Value(name string) (ent.Value, error) {
	return ar.selectValues.Get(name)
}

// Update returns a builder for updating this AbuseReport.
// Note that you need to call AbuseReport.Unwrap() before calling this method if this AbuseReport
// was returned from a transaction, and the transaction was committed or rolled back.
func (ar *AbuseReport) Update() *AbuseReportUpdateOne {
	return NewAbuseReportClient(ar.config).UpdateOne(ar)
}

// Unwrap unwraps the AbuseReport entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ar *AbuseReport) Unwrap() *AbuseReport {
	_tx, ok := ar.config.driver.(*txDriver)
	if !ok {
		panic("ent: AbuseReport is not a transactional entity")
	}
	ar.config.driver = _tx.drv
	return ar
}

// String implements the fmt.Stringer.
func (ar *AbuseReport) String() string {
	var builder strings.Builder
	builder.WriteString("AbuseReport(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ar.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ar.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ar.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := ar.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("reporter_id=")
	builder.WriteString(fmt.Sprintf("%v", ar.ReporterID))
	builder.WriteString(", ")
	builder.WriteString("reporter_email=")
	builder.WriteString(ar.ReporterEmail)
	builder.WriteString(", ")
	builder.WriteString("target_type=")
	builder.WriteString(ar.TargetType)
	builder.WriteString(", ")
	builder.WriteString("target_id=")
	builder.WriteString(fmt.Sprintf("%v", ar.TargetID))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(fmt.Sprintf("%v", ar.Reason))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(ar.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(ar.Status)
	builder.WriteString(", ")
	builder.WriteString("admin_note=")
	builder.WriteString(ar.AdminNote)
	builder.WriteByte(')')
	return builder.String()
}

// AbuseReports is a parsable slice of AbuseReport.
type AbuseReports []*AbuseReport
