// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/activityevent"
)

// ActivityEventCreate is the builder for creating a ActivityEvent entity.
type ActivityEventCreate struct {
	config
	mutation *ActivityEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (aec *ActivityEventCreate) SetCreatedAt(t time.Time) *ActivityEventCreate {
	aec.mutation.SetCreatedAt(t)
	return aec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aec *ActivityEventCreate) SetNillableCreatedAt(t *time.Time) *ActivityEventCreate {
	if t != nil {
		aec.SetCreatedAt(*t)
	}
	return aec
}

// SetUpdatedAt sets the "updated_at" field.
func (aec *ActivityEventCreate) SetUpdatedAt(t time.Time) *ActivityEventCreate {
	aec.mutation.SetUpdatedAt(t)
	return aec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (aec *ActivityEventCreate) SetNillableUpdatedAt(t *time.Time) *ActivityEventCreate {
	if t != nil {
		aec.SetUpdatedAt(*t)
	}
	return aec
}

// SetDeletedAt sets the "deleted_at" field.
func (aec *ActivityEventCreate) SetDeletedAt(t time.Time) *ActivityEventCreate {
	aec.mutation.SetDeletedAt(t)
	return aec
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (aec *ActivityEventCreate) SetNillableDeletedAt(t *time.Time) *ActivityEventCreate {
	if t != nil {
		aec.SetDeletedAt(*t)
	}
	return aec
}

// SetType sets the "type" field.
func (aec *ActivityEventCreate) SetType(i int) *ActivityEventCreate {
	aec.mutation.SetType(i)
	return aec
}

// SetActorID sets the "actor_id" field.
func (aec *ActivityEventCreate) SetActorID(i int) *ActivityEventCreate {
	aec.mutation.SetActorID(i)
	return aec
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (aec *ActivityEventCreate) SetNillableActorID(i *int) *ActivityEventCreate {
	if i != nil {
		aec.SetActorID(*i)
	}
	return aec
}

// SetIP sets the "ip" field.
func (aec *ActivityEventCreate) SetIP(s string) *ActivityEventCreate {
	aec.mutation.SetIP(s)
	return aec
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (aec *ActivityEventCreate) SetNillableIP(s *string) *ActivityEventCreate {
	if s != nil {
		aec.SetIP(*s)
	}
	return aec
}

// SetCid sets the "cid" field.
func (aec *ActivityEventCreate) SetCid(s string) *ActivityEventCreate {
	aec.mutation.SetCid(s)
	return aec
}

// SetNillableCid sets the "cid" field if the given value is not nil.
func (aec *ActivityEventCreate) SetNillableCid(s *string) *ActivityEventCreate {
	if s != nil {
		aec.SetCid(*s)
	}
	return aec
}

// SetFileID sets the "file_id" field.
func (aec *ActivityEventCreate) SetFileID(i int) *ActivityEventCreate {
	aec.mutation.SetFileID(i)
	return aec
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (aec *ActivityEventCreate) SetNillableFileID(i *int) *ActivityEventCreate {
	if i != nil {
		aec.SetFileID(*i)
	}
	return aec
}

// SetShareID sets the "share_id" field.
func (aec *ActivityEventCreate) SetShareID(i int) *ActivityEventCreate {
	aec.mutation.SetShareID(i)
	return aec
}

// SetNillableShareID sets the "share_id" field if the given value is not nil.
func (aec *ActivityEventCreate) SetNillableShareID(i *int) *ActivityEventCreate {
	if i != nil {
		aec.SetShareID(*i)
	}
	return aec
}

// SetExtra sets the "extra" field.
func (aec *ActivityEventCreate) SetExtra(m map[string]interface{}) *ActivityEventCreate {
	aec.mutation.SetExtra(m)
	return aec
}

// Mutation returns the ActivityEventMutation object of the builder.
func (aec *ActivityEventCreate) Mutation() *ActivityEventMutation {
	return aec.mutation
}

// Save creates the ActivityEvent in the database.
func (aec *ActivityEventCreate) Save(ctx context.Context) (*ActivityEvent, error) {
	if err := aec.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, aec.sqlSave, aec.mutation, aec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (aec *ActivityEventCreate) SaveX(ctx context.Context) *ActivityEvent {
	v, err := aec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aec *ActivityEventCreate) Exec(ctx context.Context) error {
	_, err := aec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aec *ActivityEventCreate) ExecX(ctx context.Context) {
	if err := aec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aec *ActivityEventCreate) defaults() error {
	if _, ok := aec.mutation.CreatedAt(); !ok {
		if activityevent.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized activityevent.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := activityevent.DefaultCreatedAt()
		aec.mutation.SetCreatedAt(v)
	}
	if _, ok := aec.mutation.UpdatedAt(); !ok {
		if activityevent.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized activityevent.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := activityevent.DefaultUpdatedAt()
		aec.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (aec *ActivityEventCreate) check() error {
	if _, ok := aec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ActivityEvent.created_at"`)}
	}
	if _, ok := aec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ActivityEvent.updated_at"`)}
	}
	if _, ok := aec.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "ActivityEvent.type"`)}
	}
	return nil
}

func (aec *ActivityEventCreate) sqlSave(ctx context.Context) (*ActivityEvent, error) {
	if err := aec.check(); err != nil {
		return nil, err
	}
	_node, _spec := aec.createSpec()
	if err := sqlgraph.CreateNode(ctx, aec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	aec.mutation.id = &_node.ID
	aec.mutation.done = true
	return _node, nil
}

func (aec *ActivityEventCreate) createSpec() (*ActivityEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &ActivityEvent{config: aec.config}
		_spec = sqlgraph.NewCreateSpec(activityevent.Table, sqlgraph.NewFieldSpec(activityevent.FieldID, field.TypeInt))
	)

	if id, ok := aec.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = aec.conflict
	if value, ok := aec.mutation.CreatedAt(); ok {
		_spec.SetField(activityevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := aec.mutation.UpdatedAt(); ok {
		_spec.SetField(activityevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := aec.mutation.DeletedAt(); ok {
		_spec.SetField(activityevent.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := aec.mutation.GetType(); ok {
		_spec.SetField(activityevent.FieldType, field.TypeInt, value)
		_node.Type = value
	}
	if value, ok := aec.mutation.ActorID(); ok {
		_spec.SetField(activityevent.FieldActorID, field.TypeInt, value)
		_node.ActorID = value
	}
	if value, ok := aec.mutation.IP(); ok {
		_spec.SetField(activityevent.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := aec.mutation.Cid(); ok {
		_spec.SetField(activityevent.FieldCid, field.TypeString, value)
		_node.Cid = value
	}
	if value, ok := aec.mutation.FileID(); ok {
		_spec.SetField(activityevent.FieldFileID, field.TypeInt, value)
		_node.FileID = value
	}
	if value, ok := aec.mutation.ShareID(); ok {
		_spec.SetField(activityevent.FieldShareID, field.TypeInt, value)
		_node.ShareID = value
	}
	if value, ok := aec.mutation.Extra(); ok {
		_spec.SetField(activityevent.FieldExtra, field.TypeJSON, value)
		_node.Extra = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ActivityEvent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ActivityEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (aec *ActivityEventCreate) OnConflict(opts ...sql.ConflictOption) *ActivityEventUpsertOne {
	aec.conflict = opts
	return &ActivityEventUpsertOne{
		create: aec,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ActivityEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (aec *ActivityEventCreate) OnConflictColumns(columns ...string) *ActivityEventUpsertOne {
	aec.conflict = append(aec.conflict, sql.ConflictColumns(columns...))
	return &ActivityEventUpsertOne{
		create: aec,
	}
}

type (
	// ActivityEventUpsertOne is the builder for "upsert"-ing
	//  one ActivityEvent node.
	ActivityEventUpsertOne struct {
		create *ActivityEventCreate
	}

	// ActivityEventUpsert is the "OnConflict" setter.
	ActivityEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ActivityEventUpsert) SetUpdatedAt(v time.Time) *ActivityEventUpsert {
	u.Set(activityevent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ActivityEventUpsert) UpdateUpdatedAt() *ActivityEventUpsert {
	u.SetExcluded(activityevent.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ActivityEventUpsert) SetDeletedAt(v time.Time) *ActivityEventUpsert {
	u.Set(activityevent.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ActivityEventUpsert) UpdateDeletedAt() *ActivityEventUpsert {
	u.SetExcluded(activityevent.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ActivityEventUpsert) ClearDeletedAt() *ActivityEventUpsert {
	u.SetNull(activityevent.FieldDeletedAt)
	return u
}

// SetType sets the "type" field.
func (u *ActivityEventUpsert) SetType(v int) *ActivityEventUpsert {
	u.Set(activityevent.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ActivityEventUpsert) UpdateType() *ActivityEventUpsert {
	u.SetExcluded(activityevent.FieldType)
	return u
}

// AddType adds v to the "type" field.
func (u *ActivityEventUpsert) AddType(v int) *ActivityEventUpsert {
	u.Add(activityevent.FieldType, v)
	return u
}

// SetActorID sets the "actor_id" field.
func (u *ActivityEventUpsert) SetActorID(v int) *ActivityEventUpsert {
	u.Set(activityevent.FieldActorID, v)
	return u
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *ActivityEventUpsert) UpdateActorID() *ActivityEventUpsert {
	u.SetExcluded(activityevent.FieldActorID)
	return u
}

// AddActorID adds v to the "actor_id" field.
func (u *ActivityEventUpsert) AddActorID(v int) *ActivityEventUpsert {
	u.Add(activityevent.FieldActorID, v)
	return u
}

// ClearActorID clears the value of the "actor_id" field.
func (u *ActivityEventUpsert) ClearActorID() *ActivityEventUpsert {
	u.SetNull(activityevent.FieldActorID)
	return u
}

// SetIP sets the "ip" field.
func (u *ActivityEventUpsert) SetIP(v string) *ActivityEventUpsert {
	u.Set(activityevent.FieldIP, v)
	return u
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *ActivityEventUpsert) UpdateIP() *ActivityEventUpsert {
	u.SetExcluded(activityevent.FieldIP)
	return u
}

// ClearIP clears the value of the "ip" field.
func (u *ActivityEventUpsert) ClearIP() *ActivityEventUpsert {
	u.SetNull(activityevent.FieldIP)
	return u
}

// SetCid sets the "cid" field.
func (u *ActivityEventUpsert) SetCid(v string) *ActivityEventUpsert {
	u.Set(activityevent.FieldCid, v)
	return u
}

// UpdateCid sets the "cid" field to the value that was provided on create.
func (u *ActivityEventUpsert) UpdateCid() *ActivityEventUpsert {
	u.SetExcluded(activityevent.FieldCid)
	return u
}

// ClearCid clears the value of the "cid" field.
func (u *ActivityEventUpsert) ClearCid() *ActivityEventUpsert {
	u.SetNull(activityevent.FieldCid)
	return u
}

// SetFileID sets the "file_id" field.
func (u *ActivityEventUpsert) SetFileID(v int) *ActivityEventUpsert {
	u.Set(activityevent.FieldFileID, v)
	return u
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *ActivityEventUpsert) UpdateFileID() *ActivityEventUpsert {
	u.SetExcluded(activityevent.FieldFileID)
	return u
}

// AddFileID adds v to the "file_id" field.
func (u *ActivityEventUpsert) AddFileID(v int) *ActivityEventUpsert {
	u.Add(activityevent.FieldFileID, v)
	return u
}

// ClearFileID clears the value of the "file_id" field.
func (u *ActivityEventUpsert) ClearFileID() *ActivityEventUpsert {
	u.SetNull(activityevent.FieldFileID)
	return u
}

// SetShareID sets the "share_id" field.
func (u *ActivityEventUpsert) SetShareID(v int) *ActivityEventUpsert {
	u.Set(activityevent.FieldShareID, v)
	return u
}

// UpdateShareID sets the "share_id" field to the value that was provided on create.
func (u *ActivityEventUpsert) UpdateShareID() *ActivityEventUpsert {
	u.SetExcluded(activityevent.FieldShareID)
	return u
}

// AddShareID adds v to the "share_id" field.
func (u *ActivityEventUpsert) AddShareID(v int) *ActivityEventUpsert {
	u.Add(activityevent.FieldShareID, v)
	return u
}

// ClearShareID clears the value of the "share_id" field.
func (u *ActivityEventUpsert) ClearShareID() *ActivityEventUpsert {
	u.SetNull(activityevent.FieldShareID)
	return u
}

// SetExtra sets the "extra" field.
func (u *ActivityEventUpsert) SetExtra(v map[string]interface{}) *ActivityEventUpsert {
	u.Set(activityevent.FieldExtra, v)
	return u
}

// UpdateExtra sets the "extra" field to the value that was provided on create.
func (u *ActivityEventUpsert) UpdateExtra() *ActivityEventUpsert {
	u.SetExcluded(activityevent.FieldExtra)
	return u
}

// ClearExtra clears the value of the "extra" field.
func (u *ActivityEventUpsert) ClearExtra() *ActivityEventUpsert {
	u.SetNull(activityevent.FieldExtra)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ActivityEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ActivityEventUpsertOne) UpdateNewValues() *ActivityEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(activityevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ActivityEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ActivityEventUpsertOne) Ignore() *ActivityEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ActivityEventUpsertOne) DoNothing() *ActivityEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ActivityEventCreate.OnConflict
// documentation for more info.
func (u *ActivityEventUpsertOne) Update(set func(*ActivityEventUpsert)) *ActivityEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ActivityEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ActivityEventUpsertOne) SetUpdatedAt(v time.Time) *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ActivityEventUpsertOne) UpdateUpdatedAt() *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ActivityEventUpsertOne) SetDeletedAt(v time.Time) *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ActivityEventUpsertOne) UpdateDeletedAt() *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ActivityEventUpsertOne) ClearDeletedAt() *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.ClearDeletedAt()
	})
}

// SetType sets the "type" field.
func (u *ActivityEventUpsertOne) SetType(v int) *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetType(v)
	})
}

// AddType adds v to the "type" field.
func (u *ActivityEventUpsertOne) AddType(v int) *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.AddType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ActivityEventUpsertOne) UpdateType() *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateType()
	})
}

// SetActorID sets the "actor_id" field.
func (u *ActivityEventUpsertOne) SetActorID(v int) *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetActorID(v)
	})
}

// AddActorID adds v to the "actor_id" field.
func (u *ActivityEventUpsertOne) AddActorID(v int) *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.AddActorID(v)
	})
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *ActivityEventUpsertOne) UpdateActorID() *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateActorID()
	})
}

// ClearActorID clears the value of the "actor_id" field.
func (u *ActivityEventUpsertOne) ClearActorID() *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.ClearActorID()
	})
}

// SetIP sets the "ip" field.
func (u *ActivityEventUpsertOne) SetIP(v string) *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *ActivityEventUpsertOne) UpdateIP() *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateIP()
	})
}

// ClearIP clears the value of the "ip" field.
func (u *ActivityEventUpsertOne) ClearIP() *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.ClearIP()
	})
}

// SetCid sets the "cid" field.
func (u *ActivityEventUpsertOne) SetCid(v string) *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetCid(v)
	})
}

// UpdateCid sets the "cid" field to the value that was provided on create.
func (u *ActivityEventUpsertOne) UpdateCid() *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateCid()
	})
}

// ClearCid clears the value of the "cid" field.
func (u *ActivityEventUpsertOne) ClearCid() *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.ClearCid()
	})
}

// SetFileID sets the "file_id" field.
func (u *ActivityEventUpsertOne) SetFileID(v int) *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetFileID(v)
	})
}

// AddFileID adds v to the "file_id" field.
func (u *ActivityEventUpsertOne) AddFileID(v int) *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.AddFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *ActivityEventUpsertOne) UpdateFileID() *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateFileID()
	})
}

// ClearFileID clears the value of the "file_id" field.
func (u *ActivityEventUpsertOne) ClearFileID() *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.ClearFileID()
	})
}

// SetShareID sets the "share_id" field.
func (u *ActivityEventUpsertOne) SetShareID(v int) *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetShareID(v)
	})
}

// AddShareID adds v to the "share_id" field.
func (u *ActivityEventUpsertOne) AddShareID(v int) *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.AddShareID(v)
	})
}

// UpdateShareID sets the "share_id" field to the value that was provided on create.
func (u *ActivityEventUpsertOne) UpdateShareID() *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateShareID()
	})
}

// ClearShareID clears the value of the "share_id" field.
func (u *ActivityEventUpsertOne) ClearShareID() *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.ClearShareID()
	})
}

// SetExtra sets the "extra" field.
func (u *ActivityEventUpsertOne) SetExtra(v map[string]interface{}) *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetExtra(v)
	})
}

// UpdateExtra sets the "extra" field to the value that was provided on create.
func (u *ActivityEventUpsertOne) UpdateExtra() *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateExtra()
	})
}

// ClearExtra clears the value of the "extra" field.
func (u *ActivityEventUpsertOne) ClearExtra() *ActivityEventUpsertOne {
	return u.Update(func(s *ActivityEventUpsert) {
		s.ClearExtra()
	})
}

// Exec executes the query.
func (u *ActivityEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ActivityEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ActivityEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ActivityEventUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ActivityEventUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *ActivityEventCreate) SetRawID(t int) *ActivityEventCreate {
	m.mutation.SetRawID(t)
	return m
}

// ActivityEventCreateBulk is the builder for creating many ActivityEvent entities in bulk.
type ActivityEventCreateBulk struct {
	config
	err      error
	builders []*ActivityEventCreate
	conflict []sql.ConflictOption
}

// Save creates the ActivityEvent entities in the database.
func (aecb *ActivityEventCreateBulk) Save(ctx context.Context) ([]*ActivityEvent, error) {
	if aecb.err != nil {
		return nil, aecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(aecb.builders))
	nodes := make([]*ActivityEvent, len(aecb.builders))
	mutators := make([]Mutator, len(aecb.builders))
	for i := range aecb.builders {
		func(i int, root context.Context) {
			builder := aecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActivityEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, aecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = aecb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, aecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, aecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (aecb *ActivityEventCreateBulk) SaveX(ctx context.Context) []*ActivityEvent {
	v, err := aecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aecb *ActivityEventCreateBulk) Exec(ctx context.Context) error {
	_, err := aecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aecb *ActivityEventCreateBulk) ExecX(ctx context.Context) {
	if err := aecb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ActivityEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ActivityEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (aecb *ActivityEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *ActivityEventUpsertBulk {
	aecb.conflict = opts
	return &ActivityEventUpsertBulk{
		create: aecb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ActivityEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (aecb *ActivityEventCreateBulk) OnConflictColumns(columns ...string) *ActivityEventUpsertBulk {
	aecb.conflict = append(aecb.conflict, sql.ConflictColumns(columns...))
	return &ActivityEventUpsertBulk{
		create: aecb,
	}
}

// ActivityEventUpsertBulk is the builder for "upsert"-ing
// a bulk of ActivityEvent nodes.
type ActivityEventUpsertBulk struct {
	create *ActivityEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ActivityEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ActivityEventUpsertBulk) UpdateNewValues() *ActivityEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(activityevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ActivityEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ActivityEventUpsertBulk) Ignore() *ActivityEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ActivityEventUpsertBulk) DoNothing() *ActivityEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ActivityEventCreateBulk.OnConflict
// documentation for more info.
func (u *ActivityEventUpsertBulk) Update(set func(*ActivityEventUpsert)) *ActivityEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ActivityEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ActivityEventUpsertBulk) SetUpdatedAt(v time.Time) *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ActivityEventUpsertBulk) UpdateUpdatedAt() *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ActivityEventUpsertBulk) SetDeletedAt(v time.Time) *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ActivityEventUpsertBulk) UpdateDeletedAt() *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ActivityEventUpsertBulk) ClearDeletedAt() *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.ClearDeletedAt()
	})
}

// SetType sets the "type" field.
func (u *ActivityEventUpsertBulk) SetType(v int) *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetType(v)
	})
}

// AddType adds v to the "type" field.
func (u *ActivityEventUpsertBulk) AddType(v int) *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.AddType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ActivityEventUpsertBulk) UpdateType() *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateType()
	})
}

// SetActorID sets the "actor_id" field.
func (u *ActivityEventUpsertBulk) SetActorID(v int) *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetActorID(v)
	})
}

// AddActorID adds v to the "actor_id" field.
func (u *ActivityEventUpsertBulk) AddActorID(v int) *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.AddActorID(v)
	})
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *ActivityEventUpsertBulk) UpdateActorID() *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateActorID()
	})
}

// ClearActorID clears the value of the "actor_id" field.
func (u *ActivityEventUpsertBulk) ClearActorID() *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.ClearActorID()
	})
}

// SetIP sets the "ip" field.
func (u *ActivityEventUpsertBulk) SetIP(v string) *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *ActivityEventUpsertBulk) UpdateIP() *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateIP()
	})
}

// ClearIP clears the value of the "ip" field.
func (u *ActivityEventUpsertBulk) ClearIP() *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.ClearIP()
	})
}

// SetCid sets the "cid" field.
func (u *ActivityEventUpsertBulk) SetCid(v string) *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetCid(v)
	})
}

// UpdateCid sets the "cid" field to the value that was provided on create.
func (u *ActivityEventUpsertBulk) UpdateCid() *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateCid()
	})
}

// ClearCid clears the value of the "cid" field.
func (u *ActivityEventUpsertBulk) ClearCid() *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.ClearCid()
	})
}

// SetFileID sets the "file_id" field.
func (u *ActivityEventUpsertBulk) SetFileID(v int) *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetFileID(v)
	})
}

// AddFileID adds v to the "file_id" field.
func (u *ActivityEventUpsertBulk) AddFileID(v int) *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.AddFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *ActivityEventUpsertBulk) UpdateFileID() *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateFileID()
	})
}

// ClearFileID clears the value of the "file_id" field.
func (u *ActivityEventUpsertBulk) ClearFileID() *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.ClearFileID()
	})
}

// SetShareID sets the "share_id" field.
func (u *ActivityEventUpsertBulk) SetShareID(v int) *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetShareID(v)
	})
}

// AddShareID adds v to the "share_id" field.
func (u *ActivityEventUpsertBulk) AddShareID(v int) *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.AddShareID(v)
	})
}

// UpdateShareID sets the "share_id" field to the value that was provided on create.
func (u *ActivityEventUpsertBulk) UpdateShareID() *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateShareID()
	})
}

// ClearShareID clears the value of the "share_id" field.
func (u *ActivityEventUpsertBulk) ClearShareID() *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.ClearShareID()
	})
}

// SetExtra sets the "extra" field.
func (u *ActivityEventUpsertBulk) SetExtra(v map[string]interface{}) *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.SetExtra(v)
	})
}

// UpdateExtra sets the "extra" field to the value that was provided on create.
func (u *ActivityEventUpsertBulk) UpdateExtra() *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.UpdateExtra()
	})
}

// ClearExtra clears the value of the "extra" field.
func (u *ActivityEventUpsertBulk) ClearExtra() *ActivityEventUpsertBulk {
	return u.Update(func(s *ActivityEventUpsert) {
		s.ClearExtra()
	})
}

// Exec executes the query.
func (u *ActivityEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ActivityEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ActivityEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ActivityEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
