// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloudreve/Cloudreve/v4/ent/invitationcode"
)

// InvitationCode is the model entity for the InvitationCode schema.
type InvitationCode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int `json:"group_id,omitempty"`
	// MaxUses holds the value of the "max_uses" field.
	MaxUses int `json:"max_uses,omitempty"`
	// UsedCount holds the value of the "used_count" field.
	UsedCount int `json:"used_count,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt    *time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvitationCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invitationcode.FieldID, invitationcode.FieldGroupID, invitationcode.FieldMaxUses, invitationcode.FieldUsedCount:
			values[i] = new(sql.NullInt64)
		case invitationcode.FieldCode:
			values[i] = new(sql.NullString)
		case invitationcode.FieldCreatedAt, invitationcode.FieldUpdatedAt, invitationcode.FieldDeletedAt, invitationcode.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvitationCode fields.
func (ic *InvitationCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invitationcode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ic.ID = int(value.Int64)
		case invitationcode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ic.CreatedAt = value.Time
			}
		case invitationcode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ic.UpdatedAt = value.Time
			}
		case invitationcode.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				ic.DeletedAt = new(time.Time)
				*ic.DeletedAt = value.Time
			}
		case invitationcode.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				ic.Code = value.String
			}
		case invitationcode.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				ic.GroupID = int(value.Int64)
			}
		case invitationcode.FieldMaxUses:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_uses", values[i])
			} else if value.Valid {
				ic.MaxUses = int(value.Int64)
			}
		case invitationcode.FieldUsedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field used_count", values[i])
			} else if value.Valid {
				ic.UsedCount = int(value.Int64)
			}
		case invitationcode.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				ic.ExpiresAt = new(time.Time)
				*ic.ExpiresAt = value.Time
			}
		default:
			ic.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvitationCode.
// This includes values selected through modifiers, order, etc.
func (ic *InvitationCode) Value(name string) (ent.Value, error) {
	return ic.selectValues.Get(name)
}

// Update returns a builder for updating this InvitationCode.
// Note that you need to call InvitationCode.Unwrap() before calling this method if this InvitationCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (ic *InvitationCode) Update() *InvitationCodeUpdateOne {
	return NewInvitationCodeClient(ic.config).UpdateOne(ic)
}

// Unwrap unwraps the InvitationCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ic *InvitationCode) Unwrap() *InvitationCode {
	_tx, ok := ic.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvitationCode is not a transactional entity")
	}
	ic.config.driver = _tx.drv
	return ic
}

// String implements the fmt.Stringer.
func (ic *InvitationCode) String() string {
	var builder strings.Builder
	builder.WriteString("InvitationCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ic.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ic.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ic.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := ic.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(ic.Code)
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", ic.GroupID))
	builder.WriteString(", ")
	builder.WriteString("max_uses=")
	builder.WriteString(fmt.Sprintf("%v", ic.MaxUses))
	builder.WriteString(", ")
	builder.WriteString("used_count=")
	builder.WriteString(fmt.Sprintf("%v", ic.UsedCount))
	builder.WriteString(", ")
	if v := ic.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// InvitationCodes is a parsable slice of InvitationCode.
type InvitationCodes []*InvitationCode
