// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloudreve/Cloudreve/v4/ent/share"
	"github.com/cloudreve/Cloudreve/v4/ent/sharepurchase"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// SharePurchase is the model entity for the SharePurchase schema.
type SharePurchase struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// ShareID holds the value of the "share_id" field.
	ShareID int `json:"share_id,omitempty"`
	// BuyerID holds the value of the "buyer_id" field.
	BuyerID int `json:"buyer_id,omitempty"`
	// Points holds the value of the "points" field.
	Points int `json:"points,omitempty"`
	// Ticket holds the value of the "ticket" field.
	Ticket string `json:"ticket,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SharePurchaseQuery when eager-loading is set.
	Edges        SharePurchaseEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SharePurchaseEdges holds the relations/edges for other nodes in the graph.
type SharePurchaseEdges struct {
	// Share holds the value of the share edge.
	Share *Share `json:"share,omitempty"`
	// Buyer holds the value of the buyer edge.
	Buyer *User `json:"buyer,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ShareOrErr returns the Share value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SharePurchaseEdges) ShareOrErr() (*Share, error) {
	if e.loadedTypes[0] {
		if e.Share == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: share.Label}
		}
		return e.Share, nil
	}
	return nil, &NotLoadedError{edge: "share"}
}

// BuyerOrErr returns the Buyer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SharePurchaseEdges) BuyerOrErr() (*User, error) {
	if e.loadedTypes[1] {
		if e.Buyer == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Buyer, nil
	}
	return nil, &NotLoadedError{edge: "buyer"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SharePurchase) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sharepurchase.FieldID, sharepurchase.FieldShareID, sharepurchase.FieldBuyerID, sharepurchase.FieldPoints:
			values[i] = new(sql.NullInt64)
		case sharepurchase.FieldTicket:
			values[i] = new(sql.NullString)
		case sharepurchase.FieldCreatedAt, sharepurchase.FieldUpdatedAt, sharepurchase.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SharePurchase fields.
func (sp *SharePurchase) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sharepurchase.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sp.ID = int(value.Int64)
		case sharepurchase.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sp.CreatedAt = value.Time
			}
		case sharepurchase.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				sp.UpdatedAt = value.Time
			}
		case sharepurchase.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				sp.DeletedAt = new(time.Time)
				*sp.DeletedAt = value.Time
			}
		case sharepurchase.FieldShareID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field share_id", values[i])
			} else if value.Valid {
				sp.ShareID = int(value.Int64)
			}
		case sharepurchase.FieldBuyerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field buyer_id", values[i])
			} else if value.Valid {
				sp.BuyerID = int(value.Int64)
			}
		case sharepurchase.FieldPoints:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field points", values[i])
			} else if value.Valid {
				sp.Points = int(value.Int64)
			}
		case sharepurchase.FieldTicket:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ticket", values[i])
			} else if value.Valid {
				sp.Ticket = value.String
			}
		default:
			sp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SharePurchase.
// This includes values selected through modifiers, order, etc.
func (sp *SharePurchase) Value(name string) (ent.Value, error) {
	return sp.selectValues.Get(name)
}

// QueryShare queries the "share" edge of the SharePurchase entity.
func (sp *SharePurchase) QueryShare() *ShareQuery {
	return NewSharePurchaseClient(sp.config).QueryShare(sp)
}

// QueryBuyer queries the "buyer" edge of the SharePurchase entity.
func (sp *SharePurchase) QueryBuyer() *UserQuery {
	return NewSharePurchaseClient(sp.config).QueryBuyer(sp)
}

// Update returns a builder for updating this SharePurchase.
// Note that you need to call SharePurchase.Unwrap() before calling this method if this SharePurchase
// was returned from a transaction, and the transaction was committed or rolled back.
func (sp *SharePurchase) Update() *SharePurchaseUpdateOne {
	return NewSharePurchaseClient(sp.config).UpdateOne(sp)
}

// Unwrap unwraps the SharePurchase entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sp *SharePurchase) Unwrap() *SharePurchase {
	_tx, ok := sp.config.driver.(*txDriver)
	if !ok {
		panic("ent: SharePurchase is not a transactional entity")
	}
	sp.config.driver = _tx.drv
	return sp
}

// String implements the fmt.Stringer.
func (sp *SharePurchase) String() string {
	var builder strings.Builder
	builder.WriteString("SharePurchase(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sp.ID))
	builder.WriteString("created_at=")
	builder.WriteString(sp.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(sp.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := sp.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("share_id=")
	builder.WriteString(fmt.Sprintf("%v", sp.ShareID))
	builder.WriteString(", ")
	builder.WriteString("buyer_id=")
	builder.WriteString(fmt.Sprintf("%v", sp.BuyerID))
	builder.WriteString(", ")
	builder.WriteString("points=")
	builder.WriteString(fmt.Sprintf("%v", sp.Points))
	builder.WriteString(", ")
	builder.WriteString("ticket=")
	builder.WriteString(sp.Ticket)
	builder.WriteByte(')')
	return builder.String()
}

// SetShare manually set the edge as loaded state.
func (e *SharePurchase) SetShare(v *Share) {
	e.Edges.Share = v
	e.Edges.loadedTypes[0] = true
}

// SetBuyer manually set the edge as loaded state.
func (e *SharePurchase) SetBuyer(v *User) {
	e.Edges.Buyer = v
	e.Edges.loadedTypes[1] = true
}

// SharePurchases is a parsable slice of SharePurchase.
type SharePurchases []*SharePurchase
