// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/sku"
)

// SkuUpdate is the builder for updating Sku entities.
type SkuUpdate struct {
	config
	hooks    []Hook
	mutation *SkuMutation
}

// Where appends a list predicates to the SkuUpdate builder.
func (su *SkuUpdate) Where(ps ...predicate.Sku) *SkuUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *SkuUpdate) SetUpdatedAt(t time.Time) *SkuUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// SetDeletedAt sets the "deleted_at" field.
func (su *SkuUpdate) SetDeletedAt(t time.Time) *SkuUpdate {
	su.mutation.SetDeletedAt(t)
	return su
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (su *SkuUpdate) SetNillableDeletedAt(t *time.Time) *SkuUpdate {
	if t != nil {
		su.SetDeletedAt(*t)
	}
	return su
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (su *SkuUpdate) ClearDeletedAt() *SkuUpdate {
	su.mutation.ClearDeletedAt()
	return su
}

// SetName sets the "name" field.
func (su *SkuUpdate) SetName(s string) *SkuUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "name" field if the given value is not nil.
func (su *SkuUpdate) SetNillableName(s *string) *SkuUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetType sets the "type" field.
func (su *SkuUpdate) SetType(s sku.Type) *SkuUpdate {
	su.mutation.SetType(s)
	return su
}

// SetNillableType sets the "type" field if the given value is not nil.
func (su *SkuUpdate) SetNillableType(s *sku.Type) *SkuUpdate {
	if s != nil {
		su.SetType(*s)
	}
	return su
}

// SetAmount sets the "amount" field.
func (su *SkuUpdate) SetAmount(i int64) *SkuUpdate {
	su.mutation.ResetAmount()
	su.mutation.SetAmount(i)
	return su
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (su *SkuUpdate) SetNillableAmount(i *int64) *SkuUpdate {
	if i != nil {
		su.SetAmount(*i)
	}
	return su
}

// AddAmount adds i to the "amount" field.
func (su *SkuUpdate) AddAmount(i int64) *SkuUpdate {
	su.mutation.AddAmount(i)
	return su
}

// SetDuration sets the "duration" field.
func (su *SkuUpdate) SetDuration(i int64) *SkuUpdate {
	su.mutation.ResetDuration()
	su.mutation.SetDuration(i)
	return su
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (su *SkuUpdate) SetNillableDuration(i *int64) *SkuUpdate {
	if i != nil {
		su.SetDuration(*i)
	}
	return su
}

// AddDuration adds i to the "duration" field.
func (su *SkuUpdate) AddDuration(i int64) *SkuUpdate {
	su.mutation.AddDuration(i)
	return su
}

// ClearDuration clears the value of the "duration" field.
func (su *SkuUpdate) ClearDuration() *SkuUpdate {
	su.mutation.ClearDuration()
	return su
}

// SetPrice sets the "price" field.
func (su *SkuUpdate) SetPrice(i int64) *SkuUpdate {
	su.mutation.ResetPrice()
	su.mutation.SetPrice(i)
	return su
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (su *SkuUpdate) SetNillablePrice(i *int64) *SkuUpdate {
	if i != nil {
		su.SetPrice(*i)
	}
	return su
}

// AddPrice adds i to the "price" field.
func (su *SkuUpdate) AddPrice(i int64) *SkuUpdate {
	su.mutation.AddPrice(i)
	return su
}

// ClearPrice clears the value of the "price" field.
func (su *SkuUpdate) ClearPrice() *SkuUpdate {
	su.mutation.ClearPrice()
	return su
}

// SetPoints sets the "points" field.
func (su *SkuUpdate) SetPoints(i int64) *SkuUpdate {
	su.mutation.ResetPoints()
	su.mutation.SetPoints(i)
	return su
}

// SetNillablePoints sets the "points" field if the given value is not nil.
func (su *SkuUpdate) SetNillablePoints(i *int64) *SkuUpdate {
	if i != nil {
		su.SetPoints(*i)
	}
	return su
}

// AddPoints adds i to the "points" field.
func (su *SkuUpdate) AddPoints(i int64) *SkuUpdate {
	su.mutation.AddPoints(i)
	return su
}

// ClearPoints clears the value of the "points" field.
func (su *SkuUpdate) ClearPoints() *SkuUpdate {
	su.mutation.ClearPoints()
	return su
}

// SetLabel sets the "label" field.
func (su *SkuUpdate) SetLabel(s string) *SkuUpdate {
	su.mutation.SetLabel(s)
	return su
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (su *SkuUpdate) SetNillableLabel(s *string) *SkuUpdate {
	if s != nil {
		su.SetLabel(*s)
	}
	return su
}

// ClearLabel clears the value of the "label" field.
func (su *SkuUpdate) ClearLabel() *SkuUpdate {
	su.mutation.ClearLabel()
	return su
}

// SetDes sets the "des" field.
func (su *SkuUpdate) SetDes(s string) *SkuUpdate {
	su.mutation.SetDes(s)
	return su
}

// SetNillableDes sets the "des" field if the given value is not nil.
func (su *SkuUpdate) SetNillableDes(s *string) *SkuUpdate {
	if s != nil {
		su.SetDes(*s)
	}
	return su
}

// ClearDes clears the value of the "des" field.
func (su *SkuUpdate) ClearDes() *SkuUpdate {
	su.mutation.ClearDes()
	return su
}

// SetEnabled sets the "enabled" field.
func (su *SkuUpdate) SetEnabled(b bool) *SkuUpdate {
	su.mutation.SetEnabled(b)
	return su
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (su *SkuUpdate) SetNillableEnabled(b *bool) *SkuUpdate {
	if b != nil {
		su.SetEnabled(*b)
	}
	return su
}

// SetWeight sets the "weight" field.
func (su *SkuUpdate) SetWeight(i int) *SkuUpdate {
	su.mutation.ResetWeight()
	su.mutation.SetWeight(i)
	return su
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (su *SkuUpdate) SetNillableWeight(i *int) *SkuUpdate {
	if i != nil {
		su.SetWeight(*i)
	}
	return su
}

// AddWeight adds i to the "weight" field.
func (su *SkuUpdate) AddWeight(i int) *SkuUpdate {
	su.mutation.AddWeight(i)
	return su
}

// Mutation returns the SkuMutation object of the builder.
func (su *SkuUpdate) Mutation() *SkuMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SkuUpdate) Save(ctx context.Context) (int, error) {
	if err := su.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SkuUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SkuUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SkuUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SkuUpdate) defaults() error {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		if sku.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sku.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sku.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (su *SkuUpdate) check() error {
	if v, ok := su.mutation.GetType(); ok {
		if err := sku.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Sku.type": %w`, err)}
		}
	}
	return nil
}

func (su *SkuUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(sku.Table, sku.Columns, sqlgraph.NewFieldSpec(sku.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(sku.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.DeletedAt(); ok {
		_spec.SetField(sku.FieldDeletedAt, field.TypeTime, value)
	}
	if su.mutation.DeletedAtCleared() {
		_spec.ClearField(sku.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(sku.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.GetType(); ok {
		_spec.SetField(sku.FieldType, field.TypeEnum, value)
	}
	if value, ok := su.mutation.Amount(); ok {
		_spec.SetField(sku.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedAmount(); ok {
		_spec.AddField(sku.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := su.mutation.Duration(); ok {
		_spec.SetField(sku.FieldDuration, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedDuration(); ok {
		_spec.AddField(sku.FieldDuration, field.TypeInt64, value)
	}
	if su.mutation.DurationCleared() {
		_spec.ClearField(sku.FieldDuration, field.TypeInt64)
	}
	if value, ok := su.mutation.Price(); ok {
		_spec.SetField(sku.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedPrice(); ok {
		_spec.AddField(sku.FieldPrice, field.TypeInt64, value)
	}
	if su.mutation.PriceCleared() {
		_spec.ClearField(sku.FieldPrice, field.TypeInt64)
	}
	if value, ok := su.mutation.Points(); ok {
		_spec.SetField(sku.FieldPoints, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedPoints(); ok {
		_spec.AddField(sku.FieldPoints, field.TypeInt64, value)
	}
	if su.mutation.PointsCleared() {
		_spec.ClearField(sku.FieldPoints, field.TypeInt64)
	}
	if value, ok := su.mutation.Label(); ok {
		_spec.SetField(sku.FieldLabel, field.TypeString, value)
	}
	if su.mutation.LabelCleared() {
		_spec.ClearField(sku.FieldLabel, field.TypeString)
	}
	if value, ok := su.mutation.Des(); ok {
		_spec.SetField(sku.FieldDes, field.TypeString, value)
	}
	if su.mutation.DesCleared() {
		_spec.ClearField(sku.FieldDes, field.TypeString)
	}
	if value, ok := su.mutation.Enabled(); ok {
		_spec.SetField(sku.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := su.mutation.Weight(); ok {
		_spec.SetField(sku.FieldWeight, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedWeight(); ok {
		_spec.AddField(sku.FieldWeight, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sku.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SkuUpdateOne is the builder for updating a single Sku entity.
type SkuUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SkuMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *SkuUpdateOne) SetUpdatedAt(t time.Time) *SkuUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// SetDeletedAt sets the "deleted_at" field.
func (suo *SkuUpdateOne) SetDeletedAt(t time.Time) *SkuUpdateOne {
	suo.mutation.SetDeletedAt(t)
	return suo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (suo *SkuUpdateOne) SetNillableDeletedAt(t *time.Time) *SkuUpdateOne {
	if t != nil {
		suo.SetDeletedAt(*t)
	}
	return suo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (suo *SkuUpdateOne) ClearDeletedAt() *SkuUpdateOne {
	suo.mutation.ClearDeletedAt()
	return suo
}

// SetName sets the "name" field.
func (suo *SkuUpdateOne) SetName(s string) *SkuUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (suo *SkuUpdateOne) SetNillableName(s *string) *SkuUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetType sets the "type" field.
func (suo *SkuUpdateOne) SetType(s sku.Type) *SkuUpdateOne {
	suo.mutation.SetType(s)
	return suo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (suo *SkuUpdateOne) SetNillableType(s *sku.Type) *SkuUpdateOne {
	if s != nil {
		suo.SetType(*s)
	}
	return suo
}

// SetAmount sets the "amount" field.
func (suo *SkuUpdateOne) SetAmount(i int64) *SkuUpdateOne {
	suo.mutation.ResetAmount()
	suo.mutation.SetAmount(i)
	return suo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (suo *SkuUpdateOne) SetNillableAmount(i *int64) *SkuUpdateOne {
	if i != nil {
		suo.SetAmount(*i)
	}
	return suo
}

// AddAmount adds i to the "amount" field.
func (suo *SkuUpdateOne) AddAmount(i int64) *SkuUpdateOne {
	suo.mutation.AddAmount(i)
	return suo
}

// SetDuration sets the "duration" field.
func (suo *SkuUpdateOne) SetDuration(i int64) *SkuUpdateOne {
	suo.mutation.ResetDuration()
	suo.mutation.SetDuration(i)
	return suo
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (suo *SkuUpdateOne) SetNillableDuration(i *int64) *SkuUpdateOne {
	if i != nil {
		suo.SetDuration(*i)
	}
	return suo
}

// AddDuration adds i to the "duration" field.
func (suo *SkuUpdateOne) AddDuration(i int64) *SkuUpdateOne {
	suo.mutation.AddDuration(i)
	return suo
}

// ClearDuration clears the value of the "duration" field.
func (suo *SkuUpdateOne) ClearDuration() *SkuUpdateOne {
	suo.mutation.ClearDuration()
	return suo
}

// SetPrice sets the "price" field.
func (suo *SkuUpdateOne) SetPrice(i int64) *SkuUpdateOne {
	suo.mutation.ResetPrice()
	suo.mutation.SetPrice(i)
	return suo
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (suo *SkuUpdateOne) SetNillablePrice(i *int64) *SkuUpdateOne {
	if i != nil {
		suo.SetPrice(*i)
	}
	return suo
}

// AddPrice adds i to the "price" field.
func (suo *SkuUpdateOne) AddPrice(i int64) *SkuUpdateOne {
	suo.mutation.AddPrice(i)
	return suo
}

// ClearPrice clears the value of the "price" field.
func (suo *SkuUpdateOne) ClearPrice() *SkuUpdateOne {
	suo.mutation.ClearPrice()
	return suo
}

// SetPoints sets the "points" field.
func (suo *SkuUpdateOne) SetPoints(i int64) *SkuUpdateOne {
	suo.mutation.ResetPoints()
	suo.mutation.SetPoints(i)
	return suo
}

// SetNillablePoints sets the "points" field if the given value is not nil.
func (suo *SkuUpdateOne) SetNillablePoints(i *int64) *SkuUpdateOne {
	if i != nil {
		suo.SetPoints(*i)
	}
	return suo
}

// AddPoints adds i to the "points" field.
func (suo *SkuUpdateOne) AddPoints(i int64) *SkuUpdateOne {
	suo.mutation.AddPoints(i)
	return suo
}

// ClearPoints clears the value of the "points" field.
func (suo *SkuUpdateOne) ClearPoints() *SkuUpdateOne {
	suo.mutation.ClearPoints()
	return suo
}

// SetLabel sets the "label" field.
func (suo *SkuUpdateOne) SetLabel(s string) *SkuUpdateOne {
	suo.mutation.SetLabel(s)
	return suo
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (suo *SkuUpdateOne) SetNillableLabel(s *string) *SkuUpdateOne {
	if s != nil {
		suo.SetLabel(*s)
	}
	return suo
}

// ClearLabel clears the value of the "label" field.
func (suo *SkuUpdateOne) ClearLabel() *SkuUpdateOne {
	suo.mutation.ClearLabel()
	return suo
}

// SetDes sets the "des" field.
func (suo *SkuUpdateOne) SetDes(s string) *SkuUpdateOne {
	suo.mutation.SetDes(s)
	return suo
}

// SetNillableDes sets the "des" field if the given value is not nil.
func (suo *SkuUpdateOne) SetNillableDes(s *string) *SkuUpdateOne {
	if s != nil {
		suo.SetDes(*s)
	}
	return suo
}

// ClearDes clears the value of the "des" field.
func (suo *SkuUpdateOne) ClearDes() *SkuUpdateOne {
	suo.mutation.ClearDes()
	return suo
}

// SetEnabled sets the "enabled" field.
func (suo *SkuUpdateOne) SetEnabled(b bool) *SkuUpdateOne {
	suo.mutation.SetEnabled(b)
	return suo
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (suo *SkuUpdateOne) SetNillableEnabled(b *bool) *SkuUpdateOne {
	if b != nil {
		suo.SetEnabled(*b)
	}
	return suo
}

// SetWeight sets the "weight" field.
func (suo *SkuUpdateOne) SetWeight(i int) *SkuUpdateOne {
	suo.mutation.ResetWeight()
	suo.mutation.SetWeight(i)
	return suo
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (suo *SkuUpdateOne) SetNillableWeight(i *int) *SkuUpdateOne {
	if i != nil {
		suo.SetWeight(*i)
	}
	return suo
}

// AddWeight adds i to the "weight" field.
func (suo *SkuUpdateOne) AddWeight(i int) *SkuUpdateOne {
	suo.mutation.AddWeight(i)
	return suo
}

// Mutation returns the SkuMutation object of the builder.
func (suo *SkuUpdateOne) Mutation() *SkuMutation {
	return suo.mutation
}

// Where appends a list predicates to the SkuUpdate builder.
func (suo *SkuUpdateOne) Where(ps ...predicate.Sku) *SkuUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SkuUpdateOne) Select(field string, fields ...string) *SkuUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Sku entity.
func (suo *SkuUpdateOne) Save(ctx context.Context) (*Sku, error) {
	if err := suo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SkuUpdateOne) SaveX(ctx context.Context) *Sku {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SkuUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SkuUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SkuUpdateOne) defaults() error {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		if sku.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sku.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sku.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (suo *SkuUpdateOne) check() error {
	if v, ok := suo.mutation.GetType(); ok {
		if err := sku.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Sku.type": %w`, err)}
		}
	}
	return nil
}

func (suo *SkuUpdateOne) sqlSave(ctx context.Context) (_node *Sku, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sku.Table, sku.Columns, sqlgraph.NewFieldSpec(sku.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sku.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sku.FieldID)
		for _, f := range fields {
			if !sku.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sku.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(sku.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.DeletedAt(); ok {
		_spec.SetField(sku.FieldDeletedAt, field.TypeTime, value)
	}
	if suo.mutation.DeletedAtCleared() {
		_spec.ClearField(sku.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(sku.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.GetType(); ok {
		_spec.SetField(sku.FieldType, field.TypeEnum, value)
	}
	if value, ok := suo.mutation.Amount(); ok {
		_spec.SetField(sku.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedAmount(); ok {
		_spec.AddField(sku.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.Duration(); ok {
		_spec.SetField(sku.FieldDuration, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedDuration(); ok {
		_spec.AddField(sku.FieldDuration, field.TypeInt64, value)
	}
	if suo.mutation.DurationCleared() {
		_spec.ClearField(sku.FieldDuration, field.TypeInt64)
	}
	if value, ok := suo.mutation.Price(); ok {
		_spec.SetField(sku.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedPrice(); ok {
		_spec.AddField(sku.FieldPrice, field.TypeInt64, value)
	}
	if suo.mutation.PriceCleared() {
		_spec.ClearField(sku.FieldPrice, field.TypeInt64)
	}
	if value, ok := suo.mutation.Points(); ok {
		_spec.SetField(sku.FieldPoints, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedPoints(); ok {
		_spec.AddField(sku.FieldPoints, field.TypeInt64, value)
	}
	if suo.mutation.PointsCleared() {
		_spec.ClearField(sku.FieldPoints, field.TypeInt64)
	}
	if value, ok := suo.mutation.Label(); ok {
		_spec.SetField(sku.FieldLabel, field.TypeString, value)
	}
	if suo.mutation.LabelCleared() {
		_spec.ClearField(sku.FieldLabel, field.TypeString)
	}
	if value, ok := suo.mutation.Des(); ok {
		_spec.SetField(sku.FieldDes, field.TypeString, value)
	}
	if suo.mutation.DesCleared() {
		_spec.ClearField(sku.FieldDes, field.TypeString)
	}
	if value, ok := suo.mutation.Enabled(); ok {
		_spec.SetField(sku.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := suo.mutation.Weight(); ok {
		_spec.SetField(sku.FieldWeight, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedWeight(); ok {
		_spec.AddField(sku.FieldWeight, field.TypeInt, value)
	}
	_node = &Sku{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sku.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
