// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/ssobinding"
)

// SsoBindingDelete is the builder for deleting a SsoBinding entity.
type SsoBindingDelete struct {
	config
	hooks    []Hook
	mutation *SsoBindingMutation
}

// Where appends a list predicates to the SsoBindingDelete builder.
func (sbd *SsoBindingDelete) Where(ps ...predicate.SsoBinding) *SsoBindingDelete {
	sbd.mutation.Where(ps...)
	return sbd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sbd *SsoBindingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sbd.sqlExec, sbd.mutation, sbd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sbd *SsoBindingDelete) ExecX(ctx context.Context) int {
	n, err := sbd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sbd *SsoBindingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ssobinding.Table, sqlgraph.NewFieldSpec(ssobinding.FieldID, field.TypeInt))
	if ps := sbd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sbd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sbd.mutation.done = true
	return affected, err
}

// SsoBindingDeleteOne is the builder for deleting a single SsoBinding entity.
type SsoBindingDeleteOne struct {
	sbd *SsoBindingDelete
}

// Where appends a list predicates to the SsoBindingDelete builder.
func (sbdo *SsoBindingDeleteOne) Where(ps ...predicate.SsoBinding) *SsoBindingDeleteOne {
	sbdo.sbd.mutation.Where(ps...)
	return sbdo
}

// Exec executes the deletion query.
func (sbdo *SsoBindingDeleteOne) Exec(ctx context.Context) error {
	n, err := sbdo.sbd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ssobinding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sbdo *SsoBindingDeleteOne) ExecX(ctx context.Context) {
	if err := sbdo.Exec(ctx); err != nil {
		panic(err)
	}
}
